### ISSUE TITLE
qjson doesnt compile with qt5

### ISSUE THREAD

**Issue by rasjani** [nomovok-opensource/cutedriver-agent_qt#24]
On platforms where qjson is being compiled - agent_qt compilation fails as qjson uses QString.toAscii()  which has been deprecated.

I'll fix this but need a pointer should i just copy over the qjson from upstream or use it as submodule or can it be just removed ?

**Comment by jppiiroinen** [comment]
Just checked the 3rdparty/qjson which seems to be 6 years old and that is only active for win32, which I have not personally used for compiling for awhile.

As far as I know, the qjson module has been part of the official Qt5 tree for few years, which would speak on the behalf of removing the qjson itself from this source tree and use the official Qt5 json related module instead.

Feel free to do a pull request, where the qjson module is removed.
