### ISSUE TITLE
Can't "make install" on mac with SIP enabled

### ISSUE THREAD

**Issue by rasjani** [nomovok-opensource/cutedriver-agent_qt#25]
make install tries to write into /usr/ and /etc/  

Atleast writing to /usr fails because SIP prevents writing there.

**Comment by jppiiroinen** [comment]
Probably you are totally right in this that we have an installation issue on OS X platform, which needs to be investigated and fixed. Which Qt version and installation package did you use?

Using testability driver also on OS X is a bit different story as well. Not sure if we have documented the steps where to copy the libraries, if those are not automatically there on the right search path. Personally I have been using ubuntu linux lts. I have a vague memory that the libraries needed to be inside the "app" under the frameworks.

If you have a possible workaround or fix for this, feel free to do a pull request. :)
