### ISSUE TITLE
Missing examples and test code

### ISSUE THREAD

**Issue by jppiiroinen** [nomovok-opensource/cutedriver-agent_qt#27]
There is code coming for this soon to
https://github.com/nomovok-opensource/cutedriver-examples

This will have some regression tests for the cutedriver and example applications.

**Comment by rasjani** [comment]
Tatu had some of the old tests for tdriver @ https://github.com/ration/tdriver_tests

**Comment by jppiiroinen** [comment]
The code has been released @ https://github.com/nomovok-opensource/cutedriver-examples

**Comment by jppiiroinen** [comment]
We should check the old tests for tdriver in another ticket.
