### ISSUE TITLE
Barebones documentation

### ISSUE THREAD

**Issue by WWDrakey** [nomovok-opensource/cutedriver-agent_qt#5]
For the component:
- Create initial non-transitory README.md
- Decide whether we want one wiki for the whole cuTeDriver, and depending on that, either:
  1) Create minimal wiki page for one component with barebones documentation and linking wiki-pages for the other components
  OR
  2) Minimal Wiki-pages for each component, with barebones documentation

**Comment by Paimen** [comment]
readme updated
